# Generated by Django 4.1.7 on 2023-04-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DDBAdminUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_code', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('secret_level', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=False)),
                ('unLock_time', models.DateTimeField()),
                ('login_history', models.JSONField()),
                ('passExpireDate', models.DateTimeField()),
                ('passChangeDate', models.DateTimeField()),
                ('sortNum', models.IntegerField()),
                ('remark', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
