# Generated by Django 4.1.7 on 2023-04-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='部门名称')),
                ('code', models.CharField(max_length=255, verbose_name='部门代码')),
                ('parentCode', models.CharField(max_length=255, verbose_name='上级部门')),
                ('deptLevel', models.CharField(max_length=255, verbose_name='部门级别')),
                ('deptDesc', models.TextField(verbose_name='部门描述')),
                ('levelDesc', models.TextField(verbose_name='机构层级描述')),
                ('enabled', models.BooleanField(verbose_name='启用')),
                ('sortNum', models.IntegerField(verbose_name='排序')),
                ('orgCode', models.CharField(max_length=255, verbose_name='所属机构')),
                ('remark', models.TextField(verbose_name='备注')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
