# Generated by Django 4.1.7 on 2023-05-23 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='部门名称')),
                ('code', models.CharField(max_length=255, verbose_name='部门代码')),
                ('parentCode', models.CharField(max_length=255, verbose_name='上级部门')),
                ('enabled', models.BooleanField(verbose_name='启用')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
