# Generated by Django 4.1.7 on 2023-08-16 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='部门名称')),
                ('code', models.CharField(max_length=255, verbose_name='部门代码')),
                ('parent_code', models.CharField(max_length=255, verbose_name='上级部门')),
                ('enabled', models.BooleanField(verbose_name='启用')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'db_table': 'ddb_department',
                'ordering': ['id'],
            },
        ),
    ]
