# Generated by Django 4.1.7 on 2023-05-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='org',
            new_name='org_id',
        ),
    ]
