# Generated by Django 4.1.7 on 2023-06-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_rename_parentcode_department_parent_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='ddb_department',
        ),
    ]
