# Generated by Django 4.1.7 on 2023-06-05 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=32)),
                ('is_show', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.menu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_menus', to='authentication.role')),
            ],
            options={
                'db_table': 'ddb_menu',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_show', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.menu')),
            ],
            options={
                'db_table': 'ddb_button',
                'ordering': ['id'],
            },
        ),
    ]
