# Generated by Django 4.1.7 on 2023-07-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='component_path',
        ),
    ]
