# Generated by Django 4.1.7 on 2023-08-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='parent_name',
        ),
        migrations.AddField(
            model_name='menu',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
