# Generated by Django 4.1.7 on 2023-08-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_menu_parent_name_menu_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
