# Generated by Django 4.1.7 on 2023-07-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_menu_component_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
    ]
