# Generated by Django 4.1.7 on 2023-06-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_group_name', models.CharField(max_length=100)),
                ('server_name', models.CharField(blank=True, max_length=100, null=True)),
                ('db_name', models.CharField(blank=True, max_length=100, null=True)),
                ('node_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'data_tree_node',
                'ordering': ['id'],
            },
        ),
    ]
