# Generated by Django 4.1.7 on 2023-08-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTreeNode',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('node_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('parent_id', models.IntegerField()),
            ],
            options={
                'db_table': 'data_tree_node',
                'ordering': ['oid'],
            },
        ),
    ]
