# Generated by Django 4.1.7 on 2023-08-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_tree_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatreenode',
            old_name='parent_id',
            new_name='parent_oid',
        ),
    ]
